<a href="https://colab.research.google.com/github/heysourin/TensorFlow-and-Computer-Vision/blob/main/Tensors%20and%20Variables(Part%201)/TensorFlow_and_CV_FCC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

# ***Initialization and Casting***

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([4, 3, 2])
print(tensor_one_d)

tf.Tensor([4 3 2], shape=(3,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([[4, 3, 2],[3, 2, 5], [12, 11, 10]])
print(tensor_two_d)

tf.Tensor(
[[ 4  3  2]
 [ 3  2  5]
 [12 11 10]], shape=(3, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([[ [4, 3, 2],
                                [3, 2, 5],
                                [12, 11, 10]
                              ],

                              [ [4, 3, 2],
                                [3, 2, 5],
                                [12, 11, 10]
                              ]
                            ])
print(tensor_three_d)

tf.Tensor(
[[[ 4  3  2]
  [ 3  2  5]
  [12 11 10]]

 [[ 4  3  2]
  [ 3  2  5]
  [12 11 10]]], shape=(2, 3, 3), dtype=int32)


# **ones_like**

In [ ]:
original_tensor = tf.constant(
    [[1,  2,  3],
     [4,  5,  6],
     [7,  8,  9]])
ones_like_tensor = tf.ones_like(original_tensor)
ones_like_tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)>

# ***Ones***

In [ ]:
one_tensor = tf.ones(
    [5, 3, 2],
    dtype=tf.dtypes.float32,
    name=None
)
one_tensor

<tf.Tensor: shape=(5, 3, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float32)>

#**Zeros**

In [ ]:
zeros_tensor = tf.zeros(
    [5, 3, 2],
    dtype=tf.dtypes.float32,
    name=None
)
zeros_tensor

<tf.Tensor: shape=(5, 3, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]], dtype=float32)>

### Shape

In [ ]:
original_tensor = tf.constant(
    [[1,  2,  3],
     [4,  5,  6],
     [7,  8,  9]])
print(original_tensor.shape)
print(tf.shape(original_tensor))

(3, 3)
tf.Tensor([3 3], shape=(2,), dtype=int32)


# **Rank: Returns rank of a tensor**

In [ ]:
tensor_rank = tf.constant(
    [[1,  2,  3],
     [4,  5,  6],
     [7,  8,  9]])
tf.rank(tensor_rank)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

#**Size: Num of different elements**

In [ ]:
tensor_size = tf.constant(
    [[1,  2,  3],
     [4,  5,  6],
     [7,  8,  9]])

tf.size(tensor_size)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

# **Normal**

In [ ]:
tf_normal = tf.random.normal(
    [3,3],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
tf_normal

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 7.9316288e-01,  8.6553556e-01, -1.9717592e-01],
       [ 2.2465920e+00, -4.1721080e-04, -2.1613482e-01],
       [-5.7420164e-01, -2.2022457e-01, -1.3635434e+00]], dtype=float32)>

In [ ]:
tf_normal2 = tf.random.normal(
    [3,3],
    mean=100.0, #!
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
tf_normal2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[100.56024 , 100.444466,  99.96849 ],
       [ 98.81578 ,  99.34578 , 101.18261 ],
       [100.21295 , 101.20579 ,  99.16629 ]], dtype=float32)>

In [ ]:
tf_normal3 = tf.random.normal(
    [3,3],
    mean=100.0, #!
    stddev=10,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
tf_normal3

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[108.58706 ,  98.85367 ,  93.934814],
       [101.46122 , 104.95883 ,  97.813385],
       [ 99.795334,  99.85503 , 102.83005 ]], dtype=float32)>

# **Uniform**

In [ ]:
tf_uniform = tf.random.uniform(
    [3,3],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
tf_uniform

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.28917706, 0.7877675 , 0.5562624 ],
       [0.15344977, 0.8632604 , 0.24915886],
       [0.8246844 , 0.4487188 , 0.94650054]], dtype=float32)>

In [ ]:
tf_uniform2 = tf.random.uniform(
    [3,3],
    minval=2, #!
    maxval=10, #!
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
tf_uniform2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[6.5176716, 9.9999075, 5.8382587],
       [5.65331  , 4.8939734, 5.3568525],
       [2.7444963, 8.1372175, 3.1233387]], dtype=float32)>

In [ ]:
tf_uniform2 = tf.random.uniform(
    [3,3],
    minval=2, #!
    maxval=8, #!
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
tf_uniform2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 2, 7],
       [7, 6, 4],
       [4, 7, 2]], dtype=int32)>

#**Basic Initializing and Casting Indexing**

In [ ]:
tensor_indexed = tf.constant([3, 6, 2, 4 ,6, 66, 7])
print(tensor_indexed)
print(tensor_indexed[1:4])
print(tensor_indexed[:4]) # from 0th to 3rd index
print(tensor_indexed[2:]) # 2 to till end
print(tensor_indexed[0:-1])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([6 2 4], shape=(3,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 2  4  6 66  7], shape=(5,), dtype=int32)
tf.Tensor([ 3  6  2  4  6 66], shape=(6,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]
                            ])
print(tensor_two_d)
print("--------------------------------------")
print(tensor_two_d[0,1])
print("--------------------------------------")
print(tensor_two_d[2,2])
print("--------------------------------------")
print(tensor_two_d[0:3,0:2])
print("--------------------------------------")
print(tensor_two_d[0:3,:])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)
--------------------------------------
tf.Tensor(2, shape=(), dtype=int32)
--------------------------------------
tf.Tensor(6, shape=(), dtype=int32)
--------------------------------------
tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)
--------------------------------------
tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
           [[1,  2,  3,  4],
            [5,  6,  7,  8],
            [9,  10,  11,  12]],

          [[13,  14,  15,  16],
           [17,  18,  19,  20],
           [21,  22,  23,  24]],

           [[23,  24,  25,  26],
            [27,  28,  29,  30],
            [31,  32,  33,  34]],

          ])
print(tensor_three_d[0,:,:])
print("--------------------------------------")
print(tensor_three_d[1,1,2])
print("--------------------------------------")
print(tensor_three_d[1,2,3])

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)
--------------------------------------
tf.Tensor(19, shape=(), dtype=int32)
--------------------------------------
tf.Tensor(24, shape=(), dtype=int32)


# **Math operations**


### Absolute values

In [ ]:
import tensorflow as tf

In [ ]:
# absolute value --> aka Modulus value in physics or math: makes all value +ve
x = tf.constant([-2.25,3.24])
print(tf.abs(x))

# absolute values for complex numbers: if a + bj then (sqrt(a^2 + b^2))
x2 = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
print(tf.abs(x2))

print("--------------")
x3 = tf.constant([-2.25 + 4.75j])
print(tf.abs(x3))

tf.Tensor([2.25 3.24], shape=(2,), dtype=float32)
tf.Tensor(
[[5.25594901]
 [6.60492241]], shape=(2, 1), dtype=float64)
--------------
tf.Tensor([5.25594901], shape=(1,), dtype=float64)


### Addition, multiply, subtract, division: Element wise

In [ ]:
x_1 = tf. constant ([5, 3,6,6,4,6], dtype = tf. int32)
x_2 = tf. constant ([7,6,2,6,7,11], dtype = tf.int32)
print(tf.add(x_1, x_2))
print(tf.multiply(x_1, x_2))
print(tf.subtract(x_1, x_2))
print(tf.divide(x_1, x_2))
print(tf.subtract(x_1, x_2))

tf.Tensor([12  9  8 12 11 17], shape=(6,), dtype=int32)
tf.Tensor([35 18 12 36 28 66], shape=(6,), dtype=int32)
tf.Tensor([-2 -3  4  0 -3 -5], shape=(6,), dtype=int32)
tf.Tensor([0.71428571 0.5        3.         1.         0.57142857 0.54545455], shape=(6,), dtype=float64)
tf.Tensor([-2 -3  4  0 -3 -5], shape=(6,), dtype=int32)


In [ ]:
x_1 = tf.constant( [5,3,6,6,4,6], dtype = tf.float32)
x_2 = tf.constant([7,6,2,6,0,11], dtype = tf.float32)
print(tf.math.divide_no_nan(x_1, x_2))

tf.Tensor([0.71428573 0.5        3.         1.         0.         0.54545456], shape=(6,), dtype=float32)


### **NOTE:**
Both tf.math.add() and tf.add() perform the same operation and will produce identical results. However, tf.add() is slightly more general and can accept additional arguments like name for naming the operation.

In [ ]:
x_1 = tf.constant([5,3,6,6,4,6], dtype = tf.float32)
x_2 = tf.constant([7], dtype = tf.float32)
print(tf.math.add(x_1, x_2))
print("-----------------------------------------------------------")
print(tf.add(x_1, x_2))

tf.Tensor([12. 10. 13. 13. 11. 13.], shape=(6,), dtype=float32)
-----------------------------------------------------------
tf.Tensor([12. 10. 13. 13. 11. 13.], shape=(6,), dtype=float32)


In [ ]:
#!
x_1 = tf.constant([[5,3,6,6,4,6]], dtype = tf.float32)
x_2 = tf.constant([[7], [5], [3]], dtype = tf.float32)
print(x_1. shape)
print (x_2. shape)
print(tf.math.multiply(x_1, x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


### Argmax

In [ ]:
A = tf.constant([1, 20, 30, 3, 6])
print(tf.math.argmax(A)) # returns the index of the max element
print(tf.math.argmin(A))

tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)


In [ ]:
B = tf.constant([[2, 20, 30, 3, 27],
                 [3, 11, 16, 8, 8],
                 [14, 45, 23, 5, 6]])
print(tf.math.argmax(B)) # here axis=0, finds index of max every col
print(tf.math.argmin(B, axis = 1))

tf.Tensor([2 2 0 1 0], shape=(5,), dtype=int64)
tf.Tensor([0 0 3], shape=(3,), dtype=int64)


### Compare

In [ ]:
x = tf.constant([2, 4])
y = tf.constant(2)
tf.math.equal(x, y)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [ ]:
x = tf.constant([2, 4])
y = tf.constant([2, 4])
tf.math.equal(x, y)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True,  True])>

### Power

In [ ]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[5, 4], [2, 3]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[32, 16],
       [ 9, 27]], dtype=int32)>

In [ ]:
tf.pow(tf.constant(2), tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
tensor_two_d = tf.constant([[4, 3, 2],
                            [3, 2, 5],
                            [12, 11, 10]])
print(tf.math.reduce_sum(tensor_two_d, axis=None, keepdims=False, name=None))

tf.Tensor(52, shape=(), dtype=int32)


In [ ]:
tensor = tf.constant([[1, 2, 3],
                      [4, 5, 6]])

print(tf.math.reduce_sum(tensor, axis=None, keepdims=False, name=None))

print(tf.math.reduce_sum(tensor, axis=1, keepdims=False, name=None))

print(tf.math.reduce_sum(tensor, axis=0, keepdims=False, name=None))

"""
axis=0 --> column wise sum
axis=1 --> row wise sum
"""

tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor([ 6 15], shape=(2,), dtype=int32)
tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [ ]:
tensor = tf.constant([[1, 2, 3],
                      [4, 5, 6]])



## **Ragged Tensor**

In [1]:
import tensorflow as tf

In [ ]:
tensor_two_d = ([[4, 3, 2],
                [3,],
                [1, 5, 6],
                [2, 3]])

# tensor_two_d = tf.constant(tensor_two_d) # Gives error
"""
You see in the above array different row has different columns,
the way TensorFlow deals with these types of data is called Ragged Tensors.
"""
tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged.shape)
print("-----------------------------------")
print(tensor_ragged)

(4, None)
-----------------------------------
<tf.RaggedTensor [[4, 3, 2], [3], [1, 5, 6], [2, 3]]>


In [ ]:
tensor_two_d = ([[4, 3, 2],
                [3,],
                [1, 5, 6],
                [2, 3]])

tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged)

<tf.RaggedTensor [[4, 3, 2], [3], [1, 5, 6], [2, 3]]>


In [2]:
print(tf.RaggedTensor.from_row_lengths(
values = [3, 1, 4, 1, 5, 9, 2, 6],
row_lengths=[4, 0, 3, 1,0]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


## **Sparse Tensors:**

In [3]:
tensor_sparse = tf.sparse.SparseTensor(
    indices = [[1,1], [3,4]], values = [11,56], dense_shape = [5,6])

In [4]:
tensor_sparse

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))

In [5]:
tf.sparse.to_dense(tensor_sparse) # Notice 11 is at(1, 1) and 56 is at (3, 4)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

## **Strings:**

In [ ]:
tf_string = tf.constant(["Hello", "there"])
tf_string

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'Hello', b'there'], dtype=object)>

In [ ]:
tf.strings.join(tf_string, separator=" ")

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello there'>

In [ ]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5], dtype=int32)>

## **Variables**

In [7]:
x = tf.constant([1,2])

In [8]:
x_var = tf.Variable(x, name='var1')
x_var

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [10]:
x_var.assign_sub([3, 4])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([-2, -2], dtype=int32)>

In [11]:
x_var.assign_add([3, 4])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [17]:
with tf.device('GPU:0'):
  x_var = tf.Variable(0.2)
  x_tensor = tf.constant(0.2)
print(x_var.device)
print(x_tensor.device)

/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0
