<a href="https://colab.research.google.com/github/heysourin/TensorFlow-and-Computer-Vision/blob/main/TensorFlow%20Basics/%20app.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

# ***Initialization and Casting***

# **ones_like**

In [ ]:
original_tensor = tf.constant(
    [[1,  2,  3],
     [4,  5,  6],
     [7,  8,  9]])
ones_like_tensor = tf.ones_like(original_tensor)
ones_like_tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)>

# ***Ones***

In [ ]:
one_tensor = tf.ones(
    [5, 3, 2],
    dtype=tf.dtypes.float32,
    name=None
)
one_tensor

<tf.Tensor: shape=(5, 3, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float32)>

#**Zeros**

In [ ]:
zeros_tensor = tf.zeros(
    [5, 3, 2],
    dtype=tf.dtypes.float32,
    name=None
)
zeros_tensor

<tf.Tensor: shape=(5, 3, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]], dtype=float32)>

### Shape

In [ ]:
original_tensor = tf.constant(
    [[1,  2,  3],
     [4,  5,  6],
     [7,  8,  9]])
print(original_tensor.shape)
print(tf.shape(original_tensor))

(3, 3)
tf.Tensor([3 3], shape=(2,), dtype=int32)


# **Rank: Returns rank of a tensor**

In [ ]:
tensor_rank = tf.constant(
    [[1,  2,  3],
     [4,  5,  6],
     [7,  8,  9]])
tf.rank(tensor_rank)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

#**Size: Num of different elements**

In [ ]:
tensor_size = tf.constant(
    [[1,  2,  3],
     [4,  5,  6],
     [7,  8,  9]])

tf.size(tensor_size)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

# **Normal**

In [ ]:
tf_normal = tf.random.normal(
    [3,3],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
tf_normal

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 7.9316288e-01,  8.6553556e-01, -1.9717592e-01],
       [ 2.2465920e+00, -4.1721080e-04, -2.1613482e-01],
       [-5.7420164e-01, -2.2022457e-01, -1.3635434e+00]], dtype=float32)>

In [ ]:
tf_normal2 = tf.random.normal(
    [3,3],
    mean=100.0, #!
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
tf_normal2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[100.56024 , 100.444466,  99.96849 ],
       [ 98.81578 ,  99.34578 , 101.18261 ],
       [100.21295 , 101.20579 ,  99.16629 ]], dtype=float32)>

In [ ]:
tf_normal3 = tf.random.normal(
    [3,3],
    mean=100, #!
    stddev=1,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
tf_normal3

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 99.70542 ,  99.585495, 100.38153 ],
       [ 99.544846, 101.30557 ,  98.84006 ],
       [ 99.85135 ,  99.42676 ,  99.16352 ]], dtype=float32)>

# **Uniform**

In [ ]:
tf_uniform = tf.random.uniform(
    [3,3],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
tf_uniform

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.28917706, 0.7877675 , 0.5562624 ],
       [0.15344977, 0.8632604 , 0.24915886],
       [0.8246844 , 0.4487188 , 0.94650054]], dtype=float32)>

In [ ]:
tf_uniform2 = tf.random.uniform(
    [3,3],
    minval=2, #!
    maxval=10, #!
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
tf_uniform2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[6.5176716, 9.9999075, 5.8382587],
       [5.65331  , 4.8939734, 5.3568525],
       [2.7444963, 8.1372175, 3.1233387]], dtype=float32)>

In [ ]:
tf_uniform2 = tf.random.uniform(
    [3,3],
    minval=2, #!
    maxval=8, #!
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
tf_uniform2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 2, 7],
       [7, 6, 4],
       [4, 7, 2]], dtype=int32)>

#**Basic Initializing and Casting Indexing**

In [7]:
tensor_indexed = tf.constant([3, 6, 2, 4 ,6, 66, 7])
print(tensor_indexed)
print(tensor_indexed[1:4])
print(tensor_indexed[:4]) # from 0th to 3rd index
print(tensor_indexed[2:]) # 2 to till end
print(tensor_indexed[0:-1])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([6 2 4], shape=(3,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([ 2  4  6 66  7], shape=(5,), dtype=int32)
tf.Tensor([ 3  6  2  4  6 66], shape=(6,), dtype=int32)


In [15]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]
                            ])
print(tensor_two_d)
print("--------------------------------------")
print(tensor_two_d[0,1])
print("--------------------------------------")
print(tensor_two_d[2,2])
print("--------------------------------------")
print(tensor_two_d[0:3,0:2])
print("--------------------------------------")
print(tensor_two_d[0:3,:])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)
--------------------------------------
tf.Tensor(2, shape=(), dtype=int32)
--------------------------------------
tf.Tensor(6, shape=(), dtype=int32)
--------------------------------------
tf.Tensor(
[[1 2]
 [3 5]
 [1 5]], shape=(3, 2), dtype=int32)
--------------------------------------
tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)


In [4]:
tensor_three_d = tf.constant([
           [[1,  2,  3,  4],
            [5,  6,  7,  8],
            [9,  10,  11,  12]],

          [[13,  14,  15,  16],
           [17,  18,  19,  20],
           [21,  22,  23,  24]],

           [[23,  24,  25,  26],
            [27,  28,  29,  30],
            [31,  32,  33,  34]],

          ])
print(tensor_three_d[0,:,:])
print(tensor_three_d[1,1,2])
print(tensor_three_d[1,1,2])

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)
tf.Tensor(19, shape=(), dtype=int32)


# **Math operations**


### Absolute values

In [7]:
# absolute value --> aka Modulus value in physics or math: makes all value +ve
x = tf.constant([-2.25,3.24])
print(tf.abs(x))

# absolute values for complex numbers: if a + bj then (sqrt(a^2 + b^2))
x2 = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
print(tf.abs(x2))

tf.Tensor([2.25 3.24], shape=(2,), dtype=float32)
tf.Tensor(
[[5.25594901]
 [6.60492241]], shape=(2, 1), dtype=float64)


### Addition, multiply, subtract, division: Element wise

In [11]:
x_1 = tf. constant ([5, 3,6,6,4,6], dtype = tf. int32)
x_2 = tf. constant ([7,6,2,6,7,11], dtype = tf.int32)
print(tf.add(x_1, x_2))
print(tf.multiply(x_1, x_2))
print(tf.subtract(x_1, x_2))
print(tf.divide(x_1, x_2))
print(tf.subtract(x_1, x_2))

tf.Tensor([12  9  8 12 11 17], shape=(6,), dtype=int32)
tf.Tensor([35 18 12 36 28 66], shape=(6,), dtype=int32)
tf.Tensor([-2 -3  4  0 -3 -5], shape=(6,), dtype=int32)
tf.Tensor([0.71428571 0.5        3.         1.         0.57142857 0.54545455], shape=(6,), dtype=float64)


In [12]:
x_1 = tf.constant( [5,3,6,6,4,6], dtype = tf.float32)
x_2 = tf.constant([7,6,2,6,0,11], dtype = tf.float32)
print(tf.math.divide_no_nan(x_1, x_2))

tf.Tensor([0.71428573 0.5        3.         1.         0.         0.54545456], shape=(6,), dtype=float32)


In [15]:
x_1 = tf.constant([5,3,6,6,4,6], dtype = tf.float32)
x_2 = tf.constant([7], dtype = tf.float32)
print(tf.math.add(x_1, x_2))

tf.Tensor([12. 10. 13. 13. 11. 13.], shape=(6,), dtype=float32)


In [18]:
#!
x_1 = tf. constant([[5,3,6,6,4,6]], dtype = tf.float32)
x_2 = tf. constant([[7], [5], [3]], dtype = tf.float32)
print(x_1. shape)
print (x_2. shape)
print(tf.math.multiply(x_1, x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


### Argmax

In [23]:
A = tf.constant([1, 20, 30, 3, 6])
print(tf.math.argmax(A)) # returns the index of the max element
print(tf.math.argmin(A))

tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)


In [28]:
B = tf.constant([[2, 20, 30, 3, 6],
                 [3, 11, 16, 1, 8],
                 [14, 45, 23, 5, 27]])
print(tf.math.argmax(B))
print(tf.math.argmin(B, axis = 1))

tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([0 3 3], shape=(3,), dtype=int64)


### Compare

In [29]:
x = tf.constant([2, 4])
y = tf.constant(2)
tf.math.equal(x, y)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [30]:
x = tf.constant([2, 4])
y = tf.constant([2, 4])
tf.math.equal(x, y)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True,  True])>

### Power

In [32]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[5, 4], [2, 3]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[32, 16],
       [ 9, 27]], dtype=int32)>

In [33]:
tf.pow(tf.constant(2), tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [34]:
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

NameError: name 'array' is not defined